# Alternate config to run the tests using a copy of the configuration
micronaut:
  server:
    port: 8080
dbpopd:
  configuration:
    path: '../files/temp/'
  startup:
    loadDatasets: false
    parallel: false