version: "3.9"
services:
  dbpop:
    image: "cdandoy/dbpop"
    ports:
      - "7104:7104"
      - "5005:5005"
    volumes:
      - ./mssql:/var/opt/dbpop
    environment:
      - DBPOP_JDBCURL=jdbc:sqlserver://mssql;database=tempdb;trustServerCertificate=true
      - DBPOP_USERNAME=sa
      - DBPOP_PASSWORD=${DB_PASS}
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=${DB_PASS}
      - ACCEPT_EULA="Y"
  pgsql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
  oracle-express:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=${DB_PASS}
